version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6666:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local